// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUY-eWYEXZdfCn4XJp76cvm6TVX_QV28',
    appId: '1:410427289728:web:b49d97391e611b3517b665',
    messagingSenderId: '410427289728',
    projectId: 'podo-words',
    authDomain: 'podo-words.firebaseapp.com',
    storageBucket: 'podo-words.firebasestorage.app',
    measurementId: 'G-0Z5W9B1BB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjvZV52zaOLl34ASqgvmKuGR8dIdDqb4g',
    appId: '1:410427289728:android:02a82c89c47db8f617b665',
    messagingSenderId: '410427289728',
    projectId: 'podo-words',
    storageBucket: 'podo-words.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIbc0L1sskHc4b8kTUxb71xg7_4mpMFlc',
    appId: '1:410427289728:ios:688527c2c687efef17b665',
    messagingSenderId: '410427289728',
    projectId: 'podo-words',
    storageBucket: 'podo-words.firebasestorage.app',
    iosBundleId: 'com.example.podoWords',
  );
}
